services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-vanilla
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      VERSION: 1.21.1
      DIFFICULTY: normal
      SEED: 3308967159
      MOTD: "A vanilla minecraft server"
      ICON: "icon.png"
      MAX_MEMORY: 4G
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 12
      ALLOW_FLIGHT: True
      MAX_PLAYERS: 4
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
    restart: unless-stopped
  backups:
    image: itzg/mc-backup
    container_name: minecraft-backup
    depends_on:
      mc:
        condition: service_healthy
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "1h"
      PRUNE_BACKUPS_DAYS: "7"
      PAUSE_IF_NO_PLAYERS: true
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      # As an example, to backup only the world data:
      # INCLUDES: world,world_nether,world_the_end
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
